name: Tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - name: Setup
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda env update --file environment.yml --name base
      - name: Test with pytest
        run: |
          conda install -c anaconda pytest
          conda install -c conda-forge pytest-cov
          $CONDA/bin/python -m pytest -v --cov=src --cov-report=term-missing
      - name: Check types with mypy
        run: |
          conda install -c conda-forge mypy
          $CONDA/bin/mypy src
      - name: Lint with pylint
        run: |
          conda install -c anaconda pylint
          $CONDA/bin/pylint src -j 4 --reports=y
